In [3]:
import configparser
import json
import pandas as pd
import requests
import functions.open_weather as ow

In [4]:
config = configparser.ConfigParser()
config.read('example.ini')

url = config['OW']['url']
api_key = config['OW']['api_key']

cities_list = ow.string_to_list(config['data']['cities'])

api_fields = config['api_fields']

weather_df = ow.get_weather(url, api_key, cities_list, api_fields)

weather_df['dt'] = pd.to_datetime(weather_df['dt'], unit='s')

In [5]:
weather_df

,city,clouds_all,coord_lat,coord_lon,dt,main_feels_like,main_humidity,main_pressure,main_temp,sys_country,weather_description,wind_deg,wind_speed
0,Lisbon,40.0,38.7167,-9.1333,2021-04-29 09:17:01,287.57,55.0,1011.0,288.54,PT,scattered clouds,300.0,4.63
1,Porto,20.0,41.1496,-8.6110,2021-04-29 09:11:15,285.07,76.0,1009.0,285.77,PT,few clouds,360.0,3.60
2,Aveiro,40.0,40.6443,-8.6455,2021-04-29 09:18:07,287.20,72.0,1009.0,287.80,PT,scattered clouds,0.0,1.03
3,Algarve,9.0,-30.0344,-51.0791,2021-04-29 09:18:07,285.79,100.0,1023.0,285.85,BR,clear sky,100.0,0.51
4,Beja,20.0,36.7256,9.1817,2021-04-29 09:18:07,294.75,73.0,1010.0,294.64,TN,few clouds,290.0,7.20
5,Coimbra,75.0,40.2056,-8.4195,2021-04-29 09:18:07,285.43,71.0,1010.0,286.21,PT,broken clouds,330.0,5.14
6,Madrid,75.0,40.4165,-3.7026,2021-04-29 09:07:11,284.78,94.0,1008.0,285.08,ES,broken clouds,190.0,4.12
7,Los Angeles,1.0,34.0522,-118.2437,2021-04-29 09:17:15,289.00,59.0,1019.0,289.74,US,clear sky,93.0,1.20
8,Tokyo,75.0,35.6895,139.6917,2021-04-29 09:07:36,290.32,94.0,1004.0,290.11,JP,light rain,180.0,5.14
9,Seoul,0.0,37.5683,126.9778,2021-04-29 09:13:01,290.59,32.0,1003.0,291.83,KR,clear sky,310.0,1.03
10,Oslo,80.0,59.9127,10.7461,2021-04-29 09:08:35,277.90,37.0,1013.0,280.00,NO,broken clouds,44.0,2.97